### ISSUE TITLE
bintray.com is gone so Android can't build

### ISSUE THREAD

**Issue by OlofT** [andriydruk/swift-weather-app#15]
Buildscript includes
   maven { url "https://dl.bintray.com/readdle/maven" }.  
This leads to:

```
Could not GET 'https://dl.bintray.com/readdle/maven/com/readdle/swift/java/codegen/annotations/0.9.0/annotations-0.9.0.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
```

**Comment by andriydruk** [comment]
Hi, sorry for the broken dependencies in this repo
All dependencies are migrated to Maven Central and updated in the main branch

**Comment by OlofT** [comment]
Thank you! Would be super-interesting to me to get this up and running for my projects. However now the toolchain gives me errors instead... Will continue here when those are working, or if I can figure out how to use a different swift compiler...

**Comment by andriydruk** [comment]
Hi, probably some issue with your setup
Please double-check that all these steps were done before compiling the project
https://github.com/andriydruk/swift-weather-app/blob/master/.github/workflows/android-ui.yml

**Comment by OlofT** [comment]
Thanks! Yes - probably something wrong with the setup. Redoing it all from scratch and what do you know? Things are working!

Thanks again! Have a nice weekend.
